# Generated by Django 3.1.14 on 2022-09-29 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contentshub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='데이터 생성시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 데이터 변경시각')),
                ('contents', models.TextField(verbose_name='질문내용')),
                ('is_answered', models.BooleanField(default=False, verbose_name='답변 여부')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='질문 삭제여부')),
                ('deleted_at', models.DateTimeField(auto_now=True, verbose_name='질문 삭제시각')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentshub.klass', verbose_name='질문이 올라온 강의')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='질문자')),
            ],
            options={
                'db_table': 'question',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='데이터 생성시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 데이터 변경시각')),
                ('contents', models.TextField(verbose_name='답변내용')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='질문 삭제여부')),
                ('deleted_at', models.DateTimeField(auto_now=True, verbose_name='질문 삭제시각')),
                ('klass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentshub.klass', verbose_name='질문이 올라온 강의')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='community.question', verbose_name='답변이 달릴 강의')),
            ],
            options={
                'db_table': 'answer',
                'ordering': ['-created_at'],
            },
        ),
    ]
