# Generated by Django 3.1.14 on 2022-09-30 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='klass',
        ),
    ]
