# Generated by Django 3.1.14 on 2022-10-02 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_answer_klass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='질문 삭제시각'),
        ),
        migrations.AlterField(
            model_name='question',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='질문 삭제시각'),
        ),
    ]
