# Generated by Django 3.1.14 on 2022-09-29 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_name', models.CharField(max_length=20, verbose_name='강사로서의 이름')),
                ('description', models.TextField(verbose_name='강사 설명')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='강사 자격 신청자')),
            ],
            options={
                'db_table': 'master',
            },
        ),
        migrations.CreateModel(
            name='Klass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='데이터 생성시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 데이터 변경시각')),
                ('title', models.CharField(max_length=50, verbose_name='강의 제목')),
                ('description', models.TextField(verbose_name='강의 설명')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contentshub.master', verbose_name='강사 이름')),
            ],
            options={
                'db_table': 'klass',
                'ordering': ['-created_at'],
            },
        ),
    ]
