# Generated by Django 3.1.14 on 2022-09-29 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='데이터 생성시각')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='마지막 데이터 변경시각')),
                ('user_type', models.CharField(choices=[('DIRECT_SIGN_UP', 'direct'), ('KAKAO', 'kakao'), ('FACEBOOK', 'facebook'), ('APPLE', 'apple')], default=('DIRECT_SIGN_UP', 'direct'), max_length=20)),
                ('email', models.EmailField(max_length=127, unique=True, verbose_name='사용자 이메일')),
                ('username', models.CharField(max_length=10, verbose_name='사용자 이름')),
                ('is_master', models.BooleanField(default=False, verbose_name='강사유저 여부 확인')),
                ('is_active', models.BooleanField(default=True, verbose_name='유저 계정 활성화 여부 확인')),
                ('is_staff', models.BooleanField(default=False, verbose_name='관리자 페이지 접속 가능 여부 확인, 데이터 수정권한은 없음')),
                ('is_admin', models.BooleanField(default=False, verbose_name='관리자 여부 확인')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='모든 권한을 가진 슈퍼유저 여부 확인')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
